baseURL: "https://cours.sofialevinmusic.com/"
languageCode: "fr-FR"
title: "Sofía Levín Cours"
description: "Découvrez le chanteur qui existe déjà en vous !"
theme: "chant"
staticDir: "static"

markup:
  goldmark:
    renderer:
      unsafe: true