baseURL: "https://cours.sofialevinmusic.com/"
languageCode: "fr-FR"
title: "Sofía Levín Cours"
theme: "chant"
staticDir: "static"

params:
  description: "Découvrez le chanteur qui existe déjà en vous !"
  facebook: "https://www.facebook.com/sofialevincours"

markup:
  goldmark:
    renderer:
      unsafe: true